name: Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
    env:
      NEXT_PUBLIC_HOST: 'http://127.0.0.1:3000'
  lighthouse:
    name: Lighthouse CI
    id: lighthouse_metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: lighthouse mobile audit
        run: yarn lhci:mobile
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: lighthouse desktop audit
        run: yarn lhci:desktop
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
    env:
      NEXT_PUBLIC_HOST: 'http://127.0.0.1:3000'
    showMetrics:
      - name: Sticky Pull Request Comment
        uses: marocchino/sticky-pull-request-comment@v2.6.2
          with:
            header: release
            message: |
              Release ${{ github.sha }} to <https://pr-${{ github.event.number }}.example.com>
