name: Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
    env:
      NEXT_PUBLIC_HOST: 'http://127.0.0.1:3000'
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
          urls: |
            http://localhost:3000/
            http://localhost:3000/adidas
            http://localhost:3000/s?term=adidas
            http://localhost:3000/4k-philips-monitor-99988213/p
          uploadArtifacts: true
          temporaryPublicStorage: true
    env:
      NEXT_PUBLIC_HOST: 'http://127.0.0.1:3000'
